[package]
name = "tempo"
version = "0.1.0"
authors = ["Fredemus <frederik.halkjaer1@gmail.com>"]
edition = "2018"

[dependencies]
hound = "3.4.0"
byteorder = "1.3.2"
# rppal = "0.11.3"
# termios = "0.3.1"
# rustfft = "3.0.0"